# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InvPar(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error_desc: str=None):  # noqa: E501
        """InvPar - a model defined in Swagger

        :param error_desc: The error_desc of this InvPar.  # noqa: E501
        :type error_desc: str
        """
        self.swagger_types = {
            'error_desc': str
        }

        self.attribute_map = {
            'error_desc': 'errorDesc'
        }
        self._error_desc = error_desc

    @classmethod
    def from_dict(cls, dikt) -> 'InvPar':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvPar of this InvPar.  # noqa: E501
        :rtype: InvPar
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_desc(self) -> str:
        """Gets the error_desc of this InvPar.

        Description of error  # noqa: E501

        :return: The error_desc of this InvPar.
        :rtype: str
        """
        return self._error_desc

    @error_desc.setter
    def error_desc(self, error_desc: str):
        """Sets the error_desc of this InvPar.

        Description of error  # noqa: E501

        :param error_desc: The error_desc of this InvPar.
        :type error_desc: str
        """

        self._error_desc = error_desc
